name: Deploy to Tencent Cloud

on:
  push:
    branches:
      - master  # 仅在推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run deployment script via SSH
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.TENCENT_CLOUD_HOST }}  # 从 Secrets 中读取服务器 IP
          username: ${{ secrets.TENCENT_CLOUD_USER }}  # 从 Secrets 中读取用户名
          key: ${{ secrets.TENCENT_CLOUD_SSH_KEY }}  # 从 Secrets 中读取 SSH 私钥
  # SSH 私钥
          script: |
            cd /var/www/my-react-app
            git pull origin master
            npm install
            npm run build
            pm2 restart all
